name: Deployment pipeline

on:
  push:
    branches:
      - main
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: |
         cd frontend 
         npm install
