name: Deployment pipeline

on:
  push:
    branches:
      - main
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install backend
        run: npm install
      - name: npm install frontend
        run: |
         cd frontend 
         npm install
      - name: lint frontend 
        run: |
          cd frontend
          npm run lint 
      - name: build
        run: |
          cd frontend
          npm run build 
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
         command: npm run test:e2e
         start: npm start
         wait-on: http://localhost:3003
      - name: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "yatzyhazymazy"
          heroku_email: "eerojmk@gmail.com"
          healthcheck: "https://yatzyhazymazy.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         DEFAULT_BUMP: patch
